apache/cordova-coho

docs/doc-translation-process.md
* Split Translating Apache Cordova into bullets
* Applying Markdown to doc-translation-process.md
=> Doc translation process

docs/platforms-release-process.md
This is getting moved to cordova-app-hello-world release steps
=> Remove updating www template step

package.json
Updated the request module we're using
=> CB-8949 Update request module

.travis.yml, README.md, package.json
-Enable travis
-Add nsp to travis
=> CB-8950 Add NSP to travis

src/list-pulls.js
1. Supports an environment variable (`CORDOVA_GIT_ACCOUNT`) to specify `<username>:<apitoken>` to avoid hitting GitHub rate limits.
2. Uses API to get most recent comment info, if available.
=> Improvements to coho list-pulls.

src/audit-license-headers.js, src/repoutil.js
Switched to using a repository's `.ratignore` file instead of the `ratExcludes` property inside of coho.
=> CB-9109 Switching to using .ratignores

src/repo-update.js
Give precedence to Apache Git remote over github remote.
=> Make repo-update more resilient to failures while updating a repo.

package.json
https://issues.apache.org/jira/browse/CB-9962
=> CB-9962 Fixed CI builds

docs/tools-release-process.md, src/npm-link.js
=> CB-12955: Update path for npm-link and tools-release-process.md

src/npm-link.js
=> CB-12963: npm-link all dependencies

docs/tools-release-process.md
Fixed/revised tools-release-process.md
=> Fixed/revised tools-release-process.md

.travis.yml, appveyor.yml, package.json, src/main.js, src/remote-update.js, src/repo-clone.js, src/repo-update.js, src/repoutil.js, src/update-release-notes.js
=> CB-13511: added github boolean to repos that have moved over to github

src/repoutil.js
This PR updates references for device motion and device orientation plugins as inactive.
=> CB-13076 , CB-13068 : Added inactive flag for device motion and device orientation plugins

docs/platforms-release-process.md
adds a note that some command is done on `master` which could be scary and unexpected.
=> CB-13624: note that commands are applied on `master` branch

docs/app-hello-world-release-process.md, docs/code-reviews.md, docs/committer-workflow.md, docs/index.md, docs/jira-triage.md, docs/platforms-release-process.md, docs/plugins-release-process.md, docs/processing-pull-requests.md, docs/tools-release-process.md, docs/versioning-and-release-strategy.md
Revised contributor docs and fixed typos.
=> CB-13624 : revised contributor docs and fixed typos

docs/processing-pull-requests.md
... and move stuff around to make sense this way
=> CB-13828 Add Github UI as a merge option

docs/setting-up-gpg.md
=> CB-13828 Work on PGP/GPG docs

docs/platforms-release-process.md
All
- add `npm audit` step to `docs/platforms-release-process.md`
Quick author proofread
=> CB-14145 add npm audit step to platform release process

docs/tools-release-process.md
All
- add npm audit step to tools release
- quick author proofread
=> CB-14145 add npm audit step (tools release)

docs/platforms-release-process.md
All
- link `npm audit` check section in the platforms "TOC"
- Visual inspection
=> CB-14145 link npm audit check in platforms "TOC"

docs/platforms-release-process.md
All
- explicitly mark TOC section
- new section to highlight Apache release process link
- move "get buy-in" & "new JIRA issue" sections
- move "npm audit check section"
- updated title & added alternative for "outdated dependencies" section
=> Before platform release doc updates

docs/platforms-release-process.md
All
- Mark "Set release version in `package.json`" as optional
- other minor fixes
- ~~[Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database~~
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~
=> Quick doc fixes for prepare platform release

docs/platforms-release-process.md, docs/tools-release-process.md
All
Add note about `--from-tag` & `--to-tag` options for `coho update-release-notes` in `tools-release-process.md` and `platforms-release-process.md`
- Visual inspection
- ~~[Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database~~
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~
=> add update-release-notes tags note

docs/tools-release-process.md
All
Add quick tools release planning notes to `docs/tools-release-process.md`
- Visual inspection
- ~~[Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database~~
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~
=> Quick notes for tools release planning

docs/tools-release-process.md
All
Add _draft_ tools dependency graph from <https://github.com/apache/cordova-discuss/issues/101#issuecomment-402857794> by @raphinesse:
_Thanks for guidance: <https://stackoverflow.com/questions/10189356/how-to-add-screenshot-to-readmes-in-github-repository#10189374>_
_To be merged by squash if there are no objections within the next 1-2 days_
Visual inspection
- ~~[Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database~~
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~
=> Add *draft* tools dependency graph by @raphinesse

docs/versioning-and-release-strategy.md
Discovered while looking at apache/cordova#18
=> Fix command to install specific Cordova version

src/repo-update.js
=> #204 support ssh remote-urls

docs/app-hello-world-release-process.md, docs/coho-release-process.md, docs/platforms-release-process.md, docs/plugins-release-process.md, docs/release-voting.md, docs/tools-release-process.md
committer docs
- adds text for non-binding vote inclusion
This closes #208
=> GH-208 Clarify non-binding vote inclusion.

docs/platforms-release-process.md
* fix links
* fix section headers
* remove extra Makefile that does not seem to exist
=> Platform Release Process: Extra Android & iOS unit test section fixes

src/repoutil.js, src/versionutil.js
none
Electron Release Support
- Added Repo Definition
- Added Version Update Support
- [Travis CI](https://travis-ci.org/erisu/cordova-coho/builds/501911543)
=> Add Electron Support

src/audit-license-headers.js
None
Updated or Sorted Exclude Commonn RAT Pattern
None
=> Update and Sort Common RAT Exclude Patterns

docs/plugins-release-process.md
- More structure
- Move some things around
- Remove JIRA
- Add Release Label
- Fix all the commands
=> Improve plugin release process documentation

src/versionutil.js
Removes code for unsupported platforms from `versionutil.js`
Addresses part of #211
=> chore(versionutil): remove unsupported platforms

src/main.js
Rejections were not handled, error code was not adjusted accordingly.
Catch rejections in `main` print them and set `exitCode` to `1`.
Manual
=> fix(main): handle rejections, set error code

.gitignore, package.json
=> test: fix code coverage & run it by default

src/versionutil.js
All
We have recently started to try to lint as many JS files as possible. This includes the platforms' version scripts. Unfortunately `coho` updates them in a form that violates our code style.
Requires test updates from #250 to pass the tests
- Pulls out the code to update our platforms' version scripts to one location
- Updates the version script according to our style guide
Passes the refactored tests from #250
=> fix(versionutil): produce JS that passes our linting

src/versionutil.js
Update the version util to update the version information that is stored in Api.js
=> feat: update version information from Api.js

docs/coho-release-process.md, docs/processing-pull-requests.md, spec/gitutil.spec.js, src/executil.js
=> Fix spelling

package.json
Fix GitHub Actions CodeCov step.
=> ci(gh-actions): fix workflow codecov step

docs/vote-checklist.md
We should offer more step by step instructions and advice how to vote to make it easier and encourage more voters.
=> Vote checklist

package-lock.json
None
* Added `package-lock.json` w/ version 2: https://github.com/apache/cordova/issues/300
Ran `npm install` to rebuild package-lock.json
N/A
=> chore(npm): added package-lock

.github/workflows/ci.yml, .github/workflows/nightly.yml
n/a
Use latest actions & node support
Update Nightly and Push CI.
Updated all actions to latest major version.
Updated Nightly to run on node 18.
Updated Push CI's Codecov to run when successful.
n/a
=> ci: update workflow actions & node support

.github/workflows/nightly.yml
n/a
Fix incorrect actions/checkout version tag.
Changed `actions/checkout@3` to `actions/checkout@v3`
n/a
=> ci(nightly): correct actions/checkout version tag

spec/audit-license-headers.spec.js
n/a
Test timing out
Increasing the timeout interval to see if it resolves the issue
n/a
=> test(audit-license-headers): increase timeout interval

package-lock.json, package.json, spec/versionutil.spec.js
n/a
Test against the latest platforms
Bumped Dev Dependencies:
- `cordova-android@^11.0.0`
- `cordova-ios@^6.3.0`
- `cordova-windows@^7.0.1`
`npm t`
`No VERSION file exists in repo cordova-android` now prints out since the VERSION file no longer exists.
This is expected...
=> test: use lastest platforms

package-lock.json, package.json, src/create-pr.js, src/list-pulls.js, src/plugin-release.js, src/shortlog.js
n/a
Use latest `@cordova/eslint-config`
Bumped `@cordova/eslint-config@5.0.0`
Updated node engine requirement `>=16.0.0`
`npm t`
=> dep!: bump @cordova/eslint-config@^5.0.0 w/ lint fix & matching node requirement >=16.0.0

docs/README.md, docs/app-hello-world-release-process.md, docs/jira-triage.md, docs/platforms-release-process.md, docs/release-voting.md, package-lock.json, package.json, spec/versionutil.spec.js, src/create-verify-archive.js, src/repoutil.js
n/a
Remove deprecated/archived platform windows from coho.
n/a
=> feat!: remove deprecated platform windows

src/repoutil.js
n/a
Remove deprecated/archived platform ubuntu from coho.
n/a
=> feat: remove deprecated platform ubuntu

.github/workflows/nightly.yml
n/a
- Use latest workflow dependencies
- Rename secret key to follow ASF standardize project level secrets
- Updated `actions/checkout` and `actions/setup-node` to use `v4`
- Renamed `NPM_TOKEN` to `CORDOVA_NPM_TOKEN`
n/a
=> ci: update nightly

.github/workflows/ci.yml, package-lock.json, package.json, spec/audit-license-headers.spec.js, spec/executil.spec.js, spec/repoutil.spec.js, src/apputil.js, src/audit-license-headers.js, src/check-license.js, src/create-verify-archive.js, src/main.js, src/merge-pr.js, src/npm-link.js, src/platform-release.js, src/plugin-release.js, src/remote-update.js, src/repo-update.js, src/repoutil.js, src/superspawn.js, src/update-release-notes.js, src/verify-tags.js, src/versionutil.js
coho is... unloved 😬 
* Update several dependencies and replace some with built-in NodeJS APIs
* Bump the minimum NodeJS version to **20.14.0+**
(this is a dev tool not intended for public use, so that should be okay)
* Remove the code that tries to link Jira ticket IDs since we don't use Jira anymore
* Replace the code that fetches RAT with `fetch()`
* Replace `q` with standard Promises
* Get rid of almost all the `shelljs` uses, still a few to clean up around sed for versioning
* Fixes GH-239
* Fixes using `coho repo-update` with `dist` and `dist/dev` SVN repositories
There are some other quick wins that should be possible, but they are extensive enough that I didn't want to do them all in a single unreviewable PR. Things like getting rid of `jira-client` (see …
=> refactor!: Cleanup & dependency modernization
