apache/cordova-coho

.gitignore
src/audit-license-headers.js
src/check-license.js
src/create-verify-archive.js
src/flagutil.js
src/gitutil.js
src/last-week.js
src/main.js
src/print-tags.js
src/repo-clone.js
src/repoutil.js
src/update-release-notes.js

This change includes logic to handle multiple modules within a single repo, and adds specific handling for the `cordova-serve` module in the `cordova-lib` repo. It also generalizes some of the existing logic for modules within a repo (that formerly was specific to `cordova-lib`). Specific changes:
1. Adds support for repos specifying a path to their module, when it is not at the top level.
2. Adds support for a repo entry actually being a module within a repo.
3. Adds `Cordova Serve` to the list of repos, it actually being a module within the `Cordova Lib` repo.
4. When calling `computeReposFromFlag()`, the caller can request to just get repos (the default) or to get modules. If just repos, then where the list would include two entries that point to the same repo, only one is returned …

Handle multiple modules within a single repo.

---

src/verify-tags.js

The `verify-tags` command currently relies on users hitting `Ctrl+D` to trigger the end of input. However, this doesn't work in the Windows command prompt.
I've modified this to use Node's `readline` module - read the input line by line, then process when an empty line is encountered. This way, the tags can be pasted then simply press `Enter`. On Unix-like systems, `Ctrl+D` will continue to work (and if you pipe in a file that will still work), since the `EOF` will trigger the `close` event.

CB-9361 Make verify-tags working nicely with Windows command prompt.

---

package.json
src/create-verify-archive.js

This adds supports for globs to the `coho verify-archive` command, so you can pass wildcards such as:
coho verify-archive *.tgz
(which is handy, since that's what `coho create-archive` says to do :smile:).

CB-9585 Support globs with 'coho verify-archive' command.

---

src/create-verify-archive.js
src/npm-link.js

Also ensures that `cordova-common` linked properly before creating release archive
Required for https://github.com/apache/cordova-android/pull/226

CB-9782 Adds npm-link support for cordova-android

---

src/create-verify-archive.js

Take a look @vladimir-kotikov. Not sure if you were using create-verify for CI or something.

CB-9220 remove check that enforces common to be linked in lib

---

src/main.js
src/nightly.js
src/npm-link.js
src/retrieve-sha.js

CB-7904 Built nightly releases using coho
Updates code for the current version
Fixed the date format
Add 'ignore-test-failures' flag for debugging purposes
Clone repos if necessary before updating
Add lib commit SHA to the build version
Adds handling for separate CLI and LIB nightly versions unpublishing
Fixes npm-unpublish-nightly entryPoint
CB-9858 Implement Cordova Fetch Proposal
Ensure fetch and cli is properly installed/linked
Add fetch to list of tools repos
Resolve cordova-fetch location properly when npm-linking modules
[Jira issue](https://issues.apache.org/jira/browse/CB-7904)

CB-7904 Built nightly releases using coho

---

src/nightly.js
src/versionutil.js

This PR updates `coho nightly` command to pin platforms to their nightly versions in `cordova-lib/platfomsConfig.json` in order to use these nightly versions by default in `cordova platform add` command
At also ensures that platforms `cordova-*` dependencies is up to date and will be included into resultant package (for now this actual for `cordova-common` dependency only)

CB-11280 Pin nightly platforms versions

---

src/repoutil.js

This PR updates the reference for cordova-plugin-file-transfer as inactive.

CB-13119: Added inactive flag for file transfer plugin

---

src/repoutil.js

Updated reference of cordova-plugin-contacts as inactive in cordova coho

CB-13065 : Updated cordova contacts plugin reference as inactive

---

package.json
spec/flagutil.spec.js
spec/gitutil.spec.js
spec/repoutil.spec.js
spec/versionutil.spec.js
test/flagutil.test.js

All
- tests working again
- package.json updates to resolve npm audit warnings
- `npm test` passes in my local workares
- fixes originally part of #172 (1.0.1 update) pass on ~~AppVeyor CI &~~ Travis CI

CB-14145: package.json updates to resolve npm audit warnings

---

.gitignore
src/create-verify-archive.js

all
removes md5 creation, md5 is too broken
npm test
created + verified an archive

CB-14185: (tooling) Skip md5 use for create-archive

---

docs/platforms-release-process.md

Make it easier to check if a platform is ready for release
All
Make it easier to check if a platform is ready for the release process
Visual inspection

Separate check outdated dependencies for platform

---

docs/platforms-release-process.md

All
- Preserve and update platform release "Request buy-in" section with timing near the beginning, preserving blame with help from `git merge`
- Mark email address for proper `cmark` (GitHub Markdown) processing
- Clarify when to raise the JIRA issue for the platform release (after waiting for any possible objections from "Request buy-in" section)
Raised in response to <https://github.com/apache/cordova-coho/pull/181#discussion_r205843535>
- Checked for proper rendering and working cross-references in <https://github.com/brodybits/cordova-coho/blob/clarify-platform-release-buy-in-and-jira-timing/docs/platforms-release-process.md>
- Checked that original blame for "Request buy-in" section shows the original commits and not my own …

Clarify platform release buy-in and JIRA issue timing

---

docs/versioning-and-release-strategy.md

I tried to understand the documented versioning strategy. To make this easier, I made some changes:
- remove outdated information and commands
- 1 topic = 1 paragraph
- add subheadlines for structure
- fix formatting

Update Versioning Strategy

---

docs/tools-release-process.md

Part of https://github.com/apache/cordova/issues/8

Remove test instructions for browserify

---

docs/platforms-release-process.md

Part of https://github.com/apache/cordova/issues/6.

Remove instructions on how to bundle dependencies

---

src/main.js

coho
Adds `version` subcommand
Manual testing

Added version command. This closes #203

---

src/knownIssues.json

none
Electron Release
Updated Known Package License Issues for Electron.
- `color-convert`
- `speedometer`
- None

Update License Known Issues for Electron

---

src/platform-release.js

none
Improve OSX Release Support
Updated the `updateCDVAvailabilityFile` method to include OSX support.
- [Travis CI](https://travis-ci.org/erisu/cordova-coho/builds/501914654)

Update updateCDVAvailabilityFile to support OSX platform

---

README.md
src/apputil.js
src/main.js

One of the more confusing aspects of coho is that by default it runs in the parent directory of the coho install/checkout. This PR adds more output and updates the README to make this more discoverable.

Clarify working directory (-g etc)

---

docs/tools-release-process.md

Add note that cordova-common singleton rule does not apply since Cordova 9

---

src/check-npm-install-util.js
src/lazy-require-util.js
src/main.js

* Check that npm dependencies are present before other require declarations in `src/main.js`
* Move code to check npm dependencies to `src/check-npm-install-util.js` utility module
* define `lazyRequire` in `src/lazy-require-util.js`
* `var` -> `const` / `let` in `main.js`, with vertical space added before some of the `const` & `let` declarations
* fix to show correct path to run "npm install", if npm dependencies are not present
Before these changes, running `cordova-coho/coho` without running `npm install` would result in the following error output:
```
internal/modules/cjs/loader.js:582
throw err;
^
Error: Cannot find module 'chalk'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
at Function.Module._load (internal/modules/cjs/loader.js:506:25)
at …
```

Improvements to src/main.js

---

docs/platforms-release-process.md

This PR removes the outdated JIRA stuff and rpelaces it with a new release identifier. 
(It also does some general light cleanup)

Platform Release Docs: repleace JIRA with release identifier

---

src/audit-license-headers.js

with updated download link
P.S. The motivation is that the old apache-rat-0.12 download link did not seem to work.

apache-rat-0.13 download update

---

appveyor.yml

* Remove the temporary allow node 12 failures flag from AppVeyor config.
none: Will use the AppVeyor run report for validation as its config driven.

chore: remove appveyor allow node12 failure

---

src/audit-license-headers.js

This reverts the Apache RAT upgrade from v0.12 to v0.13 (see #246). This is necessary due to a bug in the file exclusion logic of RAT v0.13.
For more details see: https://issues.apache.org/jira/browse/RAT-265
Closes #247

fix(audit-license-headers): broken exclusion patterns

---

package.json
spec/versionutil.spec.js

Before, the tests for `versionutil` were basically counting calls to a ton of spies. This is bad because:
- implementation changes => tests break
- tests are not able to detect failures caused by changes in the actual platforms

test(versionutil): test on actual platforms

---

coho
package.json

This allows us to drop the dependency on `gnode`.

chore: require at least Node.js v4

---

src/gitutil.js

Until now `gitutil.stashAndPop` ran the following command for each repo:
git stash save --all --quiet "coho stash"
Beside changed and untracked files, this also stashes ignored files. In
our case that includes the `node_modules` folder. Due to the massive
amount of files in there, that command takes a decent amount of time and
can also lead to _a lot_ of CRLF warning messages, depending on your
local git configuration.
Furthermore, the new build system of `cordova-js` needs to have its
dependencies present to be able to run. But since the `cordova-js` build
is run in a `stashAndPop` block, all modules have been stashed and thus
the build always fails.
AFAICT, no invocation of `gitutil.stashAndPop` does actually _need_ to
stash ignored files. Thus we can resolve these issues by replacing …

fix(gitutil): do not stash ignored files

---

.travis.yml
appveyor.yml
package.json

We do not want to be encumbered by supporting old Node.js versions for this tool.
- Bump version to `2.0.0-dev` 
- Drop older Node.js from CI

chore: prepare next major of coho

---

package.json
spec/audit-license-headers.spec.js
src/audit-license-headers.js

Needs #258, fixes #240
Downloads and extracts Apache RAT using Node.js libraries instead of
unix-specific CLI utilities.
I've added a smoke test for the `audit-license-headers` module. CI passes on Windows.

fix(audit-license-headers): RAT tool download on Windows

---

src/audit-license-headers.js

Improve code readability
- use only single `-e` flag for RAT excludes
- factor out `.ratignore` reading
- factor out RAT downloading
- use `const` & `let`
- Manual testing
- Smoke test still passes

refactor(audit-license-headers): clean up code

---

docs/setting-up-gpg.md

N/A
GPG installation instructions were missing for Windows 
Adds link to gpg4win
I installed gpg4win on Windows and confirmed it works with `cordova-coho`
- [n/a] I've run the tests to see all new and existing tests pass
- [n/a] I added automated test coverage as appropriate for this change
- [n/a] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [n/a] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))

Add installation instructions for gpg on Windows

---

.github/workflows/nightly.yml

* Add apache license header to yaml file.
* Always have npm verbose enabled.

chore: add license header & enable npm verbose always

---

.github/workflows/nightly.yml

Saw nightly try to run off my fork so updating the config to check against the repo that triggered the action.

ci: disable nightly on forks

---

.github/workflows/nightly.yml

Bump the setup-node dependency to latest version. 
This might be the solution to resolve the failed nightly builds. The failures are originating from the dependency.
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

chore: bump actions/setup-node@v2.1.2

---

.eslintrc.yml
package.json
spec/.eslintrc.yml
spec/apputil.spec.js
spec/executil.spec.js
spec/flagutil.spec.js
spec/repoutil.spec.js
spec/versionutil.spec.js
src/check-license.js
src/create-pr.js
src/for-each.js
src/gitutil.js
src/last-week.js
src/list-pulls.js
src/list-release-urls.js
src/main.js
src/npm-publish.js
src/platform-release.js
src/plugin-release.js
src/remote-update.js
src/repoutil.js
src/shortlog.js
src/update-release-notes.js
src/versionutil.js

Code syntax cleanup
https://github.com/apache/cordova/issues/142
* replace dependencies with @cordova/eslint-config
* update eslint config
* eslint corrections
- `npm t`

refactor (eslint): use cordova-eslint

---

spec/versionutil.spec.js
src/versionutil.js

android
This PR removes the updating of Android version info from framework build.gradle.
Version info is not stored in this location anymore.
This is preperation for Cordova-Android 10 release. If there is ever a need to release on Cordova-Android 9.x or ealier, use branch `coho-20210714`.
- none

cleanup: remove updating version from framework build.gradle

---

.github/workflows/nightly.yml

Nightly is failing to publish Cordova-Android because of the new npm prepare-hook scrip that automates the building of the `cordova-js` during release.
`npm i` must be performed before `npm publish`.
Other platforms will need this change in the future once the cordova-js's new build process is added.
- n/a

fix(nightly): npm install before publish for cordova-android's js build

---

.github/workflows/nightly.yml

Nightly is failing to publish Cordova-Electron because of the new npm prepare-hook scrip that automates the building of the `cordova-js` during release.
`npm i` must be performed before `npm publish`.
Other platforms will need this change in the future once the cordova-js's new build process is added.
- n/a

fix(nightly): npm install before publish for cordova-electron's js build

---

docs/setting-up-gpg.md

- Add `Fingerprint` sub header (H3)
- Recommended rather than optional
- Add quick command to get the gpg fingerprint
P.S. This proposal was triggered by [this email on the dev mailing list](https://lists.apache.org/thread.html/6f6c96f0bf9f4c4213e19a58a7d190e707d9ec98e87f15316203bfc4%40%3Cdev.cordova.apache.org%3E)

Improve gpg fingerprint documentation

---

src/audit-license-headers.js

Ignores coverage/ files
I opted to not use `coverage` as the exclude term, as I felt that's too generic/broad and may potentially exclude files that we would want to scan.
The RAT tool also doesn't appear to support a full glob syntax, so doing something like `coverage/**` doesn't work.
So finally I choose `lcov-*` and `lcov.info`, which I feel is the safest exclude terms.
These are generated files by code coverage tools and RAT states:
> Generated files do not require license headers.
Yet these files were being checked and was creating unnecessary noise.

fix: Ignore codecov files

---

src/repoutil.js

n/a
Remove deprecated/archived platform bada & bada-wac from coho.
n/a

feat!: remove deprecated platform bada & bada-wac

---

docs/storing-repo-versions-design.md
src/platform-release.js
src/repoutil.js
src/versionutil.js

n/a
Remove deprecated/archived platform blackberry from coho.
n/a

feat!: remove deprecated platform blackberry

---

src/repo-update.js
src/repoutil.js

n/a
Remove deprecated/archived platform firefox from coho.
n/a

feat!: remove deprecated platform firefoxos

---

docs/storing-repo-versions-design.md
src/platform-release.js
src/repoutil.js

n/a
Remove deprecated/archived platform osx from coho.
n/a

feat!: remove deprecated platform osx

---

docs/storing-repo-versions-design.md
src/repoutil.js

n/a
Remove deprecated/archived platform tizen from coho.
n/a

feat: remove deprecated platform tizen

---

src/repoutil.js

n/a
Remove deprecated/archived platform fireos from coho.
n/a

feat: remove deprecated platform fireos

---

src/platform-release.js

CDVAvailability.h file was moved, so the automatic version change has not worked on last two releases, this should fix the problem.

fix: Update CDVAvailability.h path
